/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.30
 * Generated at: 2016-05-13 10:39:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages.v_005f1_005f0_005f0.student;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/media/shiv/68F0AC0BF0ABDD96/WorkStation-Zone/Ubuntu/Curiosity/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/studentsmachine/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-3.0.5.RELEASE.jar", Long.valueOf(1460277405000L));
    _jspx_dependants.put("jar:file:/media/shiv/68F0AC0BF0ABDD96/WorkStation-Zone/Ubuntu/Curiosity/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/studentsmachine/WEB-INF/lib/spring-webmvc-3.0.5.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1287571886000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1460277532000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005fform_0026_005fmodelAttribute_005fmethod_005fenctype_005fclass_005faction;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fform_005fform_0026_005fmodelAttribute_005fmethod_005fenctype_005fclass_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fform_005fform_0026_005fmodelAttribute_005fmethod_005fenctype_005fclass_005faction.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- /* ************************************\n");
      out.write(" *\n");
      out.write(" * @update:  RITESH SINGH, 4 May 2016\n");
      out.write(" * @Section: Global\n");
      out.write(" * @auth0r:  RITESH SINGH\n");
      out.write(" * @version: v.1.0.0, 4 May 2016\n");
      out.write("************************************* */\n");
      out.write(" -->\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("\t\n");
      out.write("\t<!-- Head of page -->\n");
      out.write("\t<head>\n");
      out.write("\t\t<title>Student Machine+</title>\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../../../helpers/material-lite-loader.jsp", out, false);
      out.write("<script src=\"http://maps.google.com/maps/api/js?sensor=false\"></script>\n");
      out.write("\t\t\n");
      out.write("\t</head>\n");
      out.write("\t\n");
      out.write("\t<style>\n");
      out.write("\t<!-- Square card -->\n");
      out.write("\t\t.demo-card-square.mdl-card {\n");
      out.write("\t\t  width: 320px;\n");
      out.write("\t\t  height: 320px;\n");
      out.write("\t\t}\n");
      out.write("\t\t.demo-card-square > .mdl-card__title {\n");
      out.write("\t\t  color: #fff;\n");
      out.write("\t\t  background:\n");
      out.write("\t\t    url('resources/m-lite-image/lion1.jpg') bottom right 0% no-repeat #46B6AC;\n");
      out.write("\t\t}\n");
      out.write("\t</style>\n");
      out.write("\t \n");
      out.write("\t<!-- body of page -->\n");
      out.write("\t<body style=\"background-color:#7B7D7D;\" >\n");
      out.write("\t\t<div class=\"demo-layout-waterfall mdl-layout mdl-js-layout\">\n");
      out.write("<!-- =============================My Page Header & Left-drawer======================================================= -->\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../../../helpers/header-college.jsp", out, false);
      out.write("<!-- =============================My Page Header & Left-drawer Done====================================================== -->\n");
      out.write("\t\t\n");
      out.write("\t\t\t<main class=\"mdl-layout__content\">\n");
      out.write(" <!-- =============================My Page Body============================================================ -->\t\t\t\n");
      out.write("\t\t    \t<div class=\"page-content\"> \n");
      out.write("\t\t    \t\t\t<div class=\"container\" style=\"margin-top:2%; width:100%;\" >hello/\n");
      out.write("\t\t    \t\t\t\t<div class=\"row\">\n");
      out.write("\t\t    \t\t\t\t\t<div class=\"col-sm-12\">\n");
      out.write("\t<!-- =============================My Page Card============================================================ -->\t\t\t\t\t\t      \n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"demo-card-square mdl-card mdl-shadow--8dp\" style=\"width:100%; height:100%;background-color:#EAECEE;\" >\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- <div class=\"mdl-card__title mdl-card--expand\" style=\"height:100px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t    \t<h2 class=\"mdl-card__title-text\">PROJECT-CREATE</h2>\n");
      out.write("\t\t\t\t\t\t\t\t\t  \t</div> -->\n");
      out.write("\t\t\t\t\t\t\t\t\t  \t\n");
      out.write("\t<!-- =============================My Page Card Body============================================================ -->\t\t\t\t\t\t\t\t  \t\n");
      out.write("\t\t\t\t\t\t\t\t\t  \t<div class=\"mdl-card__supporting-text\">\n");
      out.write("\t\t\t\t\t\t\t\t\t    \t\n");
      out.write("\t\t\t\t\t\t\t\t\t    \t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t\t\t    \t\t<div class=\"col-sm-12\">\n");
      out.write("\t\t\t\t\t\t\t\t\t    \t\t\t<div class=\"row\" style=\"margin-left:10%;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t    \t\t\t\t<div class=\"col-sm-12\">\n");
      out.write("\t\t\t\t\t\t\t\t\t    \t\t\t\t<!-- ============================== -->\n");
      out.write("\t\t\t\t\t\t\t\t\t    \t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t    \t\t\t\t<div id=\"login-overlay\" class=\"modal-dialog\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t      <div class=\"modal-content\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t          <div class=\"modal-header\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t              <h4 class=\"modal-title\" id=\"myModalLabel\">Sign Up to <b>curiositycollege.com</b></h4> or go back to our <a href=\"./index.jsp\">home page</a>.\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t          </div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t          <div class=\"modal-body\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t              <div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t                  <div class=\"col-xs-6\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t                      <div class=\"well\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t                         ");
      if (_jspx_meth_form_005fform_005f0(_jspx_page_context))
        return;
      out.write("</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t                  </div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t                  <div class=\"col-xs-6\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t                  \t<!-- <input type=\"file\" name=\"fileData\"> -->\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t                  \t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t                  \t<div class=\"fileinput fileinput-new\" data-provides=\"fileinput\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"fileinput-preview thumbnail\" data-trigger=\"fileinput\" style=\"width: 200px; height: 150px;\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t  <div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t    <span class=\"btn btn-default btn-file\"><span class=\"fileinput-new\">Select image</span><span class=\"fileinput-exists\">Change</span><input type=\"file\" name=\"...\"></span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t    <a href=\"#\" class=\"btn btn-default fileinput-exists\" data-dismiss=\"fileinput\">Remove</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t </div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t                  \t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t                  \t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t                  \t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t                  \t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t                  </div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t              </div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t          </div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t      </div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t  </div>\n");
      out.write("\t\t\t\t\t\t\t\t\t    \t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t    \t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t    \t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t    \t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t    \t\t\t\t<!-- ============================================= -->\n");
      out.write("\t\t\t\t\t\t\t\t\t    \t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t    \t\t\t</div>\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t    \t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t    \t</div>\t\n");
      out.write("\t\t\t\t\t\t\t\t\t  \t</div>\n");
      out.write("\t<!-- =============================My Page Card Body Done============================================================ -->\n");
      out.write("\t\t\t\t\t\t\t\t\t  \t\n");
      out.write("\t<!-- =============================My Page Card Footer============================================================ -->\t\t\t\t\t\t\t\t  \t\n");
      out.write("\t\t\t\t\t\t\t\t\t  \t\n");
      out.write("\t\t\t\t\t\t\t\t\t  \t<div class=\"mdl-card__actions mdl-card--border\">\n");
      out.write("\t\t\t\t\t\t\t\t\t    \t<a class=\"mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect\">\n");
      out.write("\t\t\t\t\t\t\t\t\t      \t\tView Updates\n");
      out.write("\t\t\t\t\t\t\t\t\t    \t</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t  \t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\n");
      out.write("\t<!-- =============================My Page Card Footer Done============================================================ -->\t\t\t\t\t\t\t\t  \t\n");
      out.write("\t\t\t\t\t\t\t\t\t  \t\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\n");
      out.write("\t<!-- =============================My Page Card Done============================================================ -->\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t    </div>\n");
      out.write("\t\t    \t\t\t\t</div>\n");
      out.write("\t\t    \t\t\t</div>\n");
      out.write("\t    \t\t</div>\n");
      out.write("<!-- =============================My Page Body Done============================================================ -->\t\t\t    \t\n");
      out.write("\t\t  \t</main>\n");
      out.write("\t\t</div>\n");
      out.write("\t</body>\n");
      out.write("</html>\n");
      out.write("<script>\n");
      out.write("\n");
      out.write("$(document).ready(function(){\n");
      out.write("\t$('.BSswitch').bootstrapSwitch('state', true);\n");
      out.write("\tgetAddress();\t\n");
      out.write("});\n");
      out.write("\n");
      out.write("\tfunction getImage(){\n");
      out.write("\t\tvar d = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ data.imageData}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\n");
      out.write("\t\tvar imageData = base64_encode(file_get_contents(d));\n");
      out.write("\t\tvar src = 'data: '+mime_content_type($image)+';base64,'+imageData;\n");
      out.write("\t\talert(src);\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tfunction getAddress(){\n");
      out.write("\t\t\n");
      out.write("\t\tvar latitudeAndLongitude=document.getElementById(\"latitudeAndLongitude\"),\n");
      out.write("\t\tlocation={\n");
      out.write("\t\t    latitude:'',\n");
      out.write("\t\t    longitude:''\n");
      out.write("\t\t};\n");
      out.write("\n");
      out.write("\t\tif (navigator.geolocation){\n");
      out.write("\t\t  navigator.geolocation.getCurrentPosition(showPosition);\n");
      out.write("\t\t}\n");
      out.write("\t\telse{\n");
      out.write("\t\t  latitudeAndLongitude.innerHTML=\"Geolocation is not supported by this browser.\";\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\tfunction showPosition(position){ \n");
      out.write("\t\t    location.latitude=position.coords.latitude;\n");
      out.write("\t\t    location.longitude=position.coords.longitude;\n");
      out.write("\t\t    latitudeAndLongitude.innerHTML=\"Latitude: \" + position.coords.latitude + \n");
      out.write("\t\t    \"<br>Longitude: \" + position.coords.longitude; \n");
      out.write("\t\t    $('#longi').val(position.coords.longitude);\n");
      out.write("\t\t    $('#lati').val(position.coords.latitude);\n");
      out.write("\t\t    \n");
      out.write("\t\t    var geocoder = new google.maps.Geocoder();\n");
      out.write("\t\t    var latLng = new google.maps.LatLng(location.latitude, location.longitude);\n");
      out.write("\n");
      out.write("\t\t if (geocoder) {\n");
      out.write("\t\t    geocoder.geocode({ 'latLng': latLng}, function (results, status) {\n");
      out.write("\t\t       if (status == google.maps.GeocoderStatus.OK) {\n");
      out.write("\t\t         console.log(results[0].formatted_address); \n");
      out.write("\t\t         $('#address').html(results[0].formatted_address);\n");
      out.write("\t\t       }\n");
      out.write("\t\t       else {\n");
      out.write("\t\t        $('#address').html('Geocoding failed: '+status);\n");
      out.write("\t\t        console.log(\"Geocoding failed: \" + status);\n");
      out.write("\t\t       }\n");
      out.write("\t\t    }); //geocoder.geocode()\n");
      out.write("\t\t  }      \n");
      out.write("\t\t} //showPosition\n");
      out.write("\t}\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_form_005fform_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:form
    org.springframework.web.servlet.tags.form.FormTag _jspx_th_form_005fform_005f0 = (org.springframework.web.servlet.tags.form.FormTag) _005fjspx_005ftagPool_005fform_005fform_0026_005fmodelAttribute_005fmethod_005fenctype_005fclass_005faction.get(org.springframework.web.servlet.tags.form.FormTag.class);
    _jspx_th_form_005fform_005f0.setPageContext(_jspx_page_context);
    _jspx_th_form_005fform_005f0.setParent(null);
    // /WEB-INF/pages/v_1_0_0/student/signup.jsp(79,38) name = modelAttribute type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005fform_005f0.setModelAttribute("collegeCreate");
    // /WEB-INF/pages/v_1_0_0/student/signup.jsp(79,38) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005fform_005f0.setAction("collegeSave");
    // /WEB-INF/pages/v_1_0_0/student/signup.jsp(79,38) null
    _jspx_th_form_005fform_005f0.setDynamicAttribute(null, "class", "form-horizontal");
    // /WEB-INF/pages/v_1_0_0/student/signup.jsp(79,38) name = method type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005fform_005f0.setMethod("post");
    // /WEB-INF/pages/v_1_0_0/student/signup.jsp(79,38) name = enctype type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005fform_005f0.setEnctype("multipart/form-data");
    int[] _jspx_push_body_count_form_005fform_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_form_005fform_005f0 = _jspx_th_form_005fform_005f0.doStartTag();
      if (_jspx_eval_form_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("<div class=\"form-group\">\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<!-- <label for=\"name\" class=\"cols-sm-2 control-label\">Your Name</label> -->\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"cols-sm-10\">\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"input-group\">\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"input-group-addon\"><i class=\"fa fa-user fa\" aria-hidden=\"true\"></i></span>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"name\" id=\"name\"  placeholder=\"Enter your Name\"/>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\" hidden>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<!-- <label for=\"currentaddress\" class=\"cols-sm-2 control-label\">Current Address</label> -->\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"cols-sm-10\">\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"input-group\">\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input id=\"longi\" name=\"longitude\" class=\"mdl-textfield__input\" type=\"text\" id=\"projectLeaderId\">\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input id=\"lati\" name=\"latitude\" class=\"mdl-textfield__input\" type=\"text\" id=\"projectLeaderId\">\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<textarea id=\"address\" name=\"address\" class=\"mdl-textfield__input\" type=\"text\" rows= \"10\" id=\"content\" style=\"background-color:#EAEDED;color:black;\" ></textarea>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<!-- <label for=\"name\" class=\"cols-sm-2 control-label\">Gender</label> -->\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"cols-sm-10\">\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"input-group\">\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"input-group-addon\"><i class=\"fa fa-user fa\" aria-hidden=\"true\"></i></span>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input id=\"TheCheckBox\" name=\"gender\"  type=\"checkbox\" data-off-text=\"Female\" data-on-text=\"Male\" checked=\"false\" class=\"BSswitch\">\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<!-- <label for=\"contactNo\" class=\"cols-sm-2 control-label\">Contact No</label> -->\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"cols-sm-10\">\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"input-group\">\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-earphone\" aria-hidden=\"true\"></i></span>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"contactNo\" id=\"contactNo\"  placeholder=\"Enter your contactNo\"/>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<!-- <label for=\"email\" class=\"cols-sm-2 control-label\">Your Email</label> -->\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"cols-sm-10\">\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"input-group\">\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"input-group-addon\"><i class=\"fa fa-envelope fa\" aria-hidden=\"true\"></i></span>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"email\" id=\"email\"  placeholder=\"Enter your Email\"/>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<!-- <label for=\"username\" class=\"cols-sm-2 control-label\">Username</label> -->\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"cols-sm-10\">\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"input-group\">\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"input-group-addon\"><i class=\"fa fa-users fa\" aria-hidden=\"true\"></i></span>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"username\" id=\"username\"  placeholder=\"Enter your Username\"/>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<!-- <label for=\"password\" class=\"cols-sm-2 control-label\">Password</label> -->\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"cols-sm-10\">\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"input-group\">\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"input-group-addon\"><i class=\"fa fa-lock fa-lg\" aria-hidden=\"true\"></i></span>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"password\" class=\"form-control\" name=\"password\" id=\"password\"  placeholder=\"Enter your Password\"/>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<!-- <label for=\"confirm\" class=\"cols-sm-2 control-label\">Confirm Password</label> -->\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"cols-sm-10\">\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"input-group\">\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"input-group-addon\"><i class=\"fa fa-lock fa-lg\" aria-hidden=\"true\"></i></span>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"password\" class=\"form-control\" name=\"confirm\" id=\"confirm\"  placeholder=\"Confirm your Password\"/>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group \">\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary btn-lg btn-block login-button\">SignUp</button>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"login-register\">\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t            <a href=\"index.php\">Login</a>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t         </div>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_form_005fform_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_form_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005fform_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005fform_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005fform_005f0.doFinally();
      _005fjspx_005ftagPool_005fform_005fform_0026_005fmodelAttribute_005fmethod_005fenctype_005fclass_005faction.reuse(_jspx_th_form_005fform_005f0);
    }
    return false;
  }
}
