/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.30
 * Generated at: 2016-05-09 08:40:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages.v_005f1_005f0_005f0.college;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-3.0.5.RELEASE.jar", Long.valueOf(1460277405000L));
    _jspx_dependants.put("jar:file:/media/shiv/68F0AC0BF0ABDD96/WorkStation-Zone/Ubuntu/Curiosity/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/collegemachine/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1460277532000L));
    _jspx_dependants.put("jar:file:/media/shiv/68F0AC0BF0ABDD96/WorkStation-Zone/Ubuntu/Curiosity/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/collegemachine/WEB-INF/lib/spring-webmvc-3.0.5.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1287571886000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- /* ************************************\r\n");
      out.write(" *\r\n");
      out.write(" * @update:  RITESH SINGH, 29 March 2016\r\n");
      out.write(" * @Section: Global\r\n");
      out.write(" * @auth0r:  RITESH SINGH\r\n");
      out.write(" * @version: v.1.0.0, 26 March 2016\r\n");
      out.write("************************************* */\r\n");
      out.write(" -->\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Head of page -->\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<title>CollegeMachine+</title>\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../../../helpers/material-lite-loader.jsp", out, false);
      out.write("</head>\r\n");
      out.write("\t\r\n");
      out.write("\t<style>\r\n");
      out.write("\t<!-- Square card -->\r\n");
      out.write("\t\t.demo-card-square.mdl-card {\r\n");
      out.write("\t\t  width: 320px;\r\n");
      out.write("\t\t  height: 320px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.demo-card-square > .mdl-card__title {\r\n");
      out.write("\t\t  color: #fff;\r\n");
      out.write("\t\t  background:\r\n");
      out.write("\t\t    url('resources/m-lite-image/lion1.jpg') bottom right 0% no-repeat #46B6AC;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("\t \r\n");
      out.write("\t<!-- body of page --><!-- #D5DBDB -->\r\n");
      out.write("\t<body style=\"background-color:#7B7D7D;\"> \r\n");
      out.write("\t\t<div class=\"demo-layout-waterfall mdl-layout mdl-js-layout\">\r\n");
      out.write("<!-- =============================My Page Header & Left-drawer======================================================= -->\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../../../helpers/header.jsp", out, false);
      out.write("<!-- =============================My Page Header & Left-drawer Done====================================================== -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<main class=\"mdl-layout__content\" >\r\n");
      out.write(" <!-- =============================My Page Body============================================================ -->\t\t\t\r\n");
      out.write("\t\t    \t<div class=\"page-content\" >\r\n");
      out.write("\t\t    \t\t\r\n");
      out.write("\t    \t\t\t<div class=\"container\" style=\"margin-top:2%; width:100%;\"  >\r\n");
      out.write("\t    \t\t\t\t<div class=\"row\">\r\n");
      out.write("\t    \t\t\t\t\t<div class=\"col-sm-12\">\r\n");
      out.write("<!-- =============================My Page Card============================================================ -->\t\t\t\t\t\t      \r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-card-square mdl-card mdl-shadow--8dp\" style=\"width:100%; height:100%;background-color:#EAECEE;\"  >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- <div class=\"mdl-card__title mdl-card--expand\" style=\"height:100px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t    \t<h2 class=\"mdl-card__title-text\">Update</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t</div> -->\t\r\n");
      out.write("<!-- =============================My Page Card Body============================================================ -->\t\t\t\t\t\t\t\t  \t\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t<div class=\"mdl-card__supporting-text\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t<!-- Colored FAB button with ripple -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"collegeCreate\"  class=\"mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored mdl-button--mini-fab\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <i class=\"material-icons\">add</i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t    \t<div class=\"row\" style=\"margin-left:10%;\"> \r\n");
      out.write("\t\t\t\t\t                    \t<div class=\"table-responsive  \">   \r\n");
      out.write("\t\t\t\t\t\t    \t\t\t   \t\t<table id=\"real\" class=\"display \">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t   \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</table>\t\r\n");
      out.write("\t\t\t\t\t                  \t\t</div>\r\n");
      out.write("\t\t\t\t\t                  \t\t\r\n");
      out.write("\t\t\t\t\t                  \t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t    \t\r\n");
      out.write("\t\t\t\t\t\t\t\t    \t\r\n");
      out.write("\t\t\t\t\t\t\t\t    \t\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t</div>\r\n");
      out.write("<!-- =============================My Page Card Body Done============================================================ -->\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\r\n");
      out.write("<!-- =============================My Page Card Footer============================================================ -->\t\t\t\t\t\t\t\t  \t\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t<div class=\"mdl-card__actions mdl-card--border\">\r\n");
      out.write("\t\t\t\t\t\t\t\t    \t<a class=\"mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect\">\r\n");
      out.write("\t\t\t\t\t\t\t\t      \t\tView Updates\r\n");
      out.write("\t\t\t\t\t\t\t\t    \t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("<!-- =============================My Page Card Footer Done============================================================ -->\t\t\t\t\t\t\t\t  \t\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("<!-- =============================My Page Card Done============================================================ -->\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t    </div>\r\n");
      out.write("\t    \t\t\t\t</div>\r\n");
      out.write("\t    \t\t\t</div>\r\n");
      out.write("\t    \t\t</div>\r\n");
      out.write("<!-- =============================My Page Body Done============================================================ -->\t\t\t    \t\r\n");
      out.write("\t\t  \t</main>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t    \r\n");
      out.write("\t\tvar tag = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${data.tag}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#real').DataTable( {\r\n");
      out.write("\t        // ajax loading data \t  \r\n");
      out.write("\t\t\t\t\"ajax\" : \"colleges?tag=\"+tag,\r\n");
      out.write("\t\t\t\t\"search\": {\r\n");
      out.write("\t\t\t\t    \"smart\": false,\r\n");
      out.write("\t\t\t\t    \"caseInsensitive\": true,\r\n");
      out.write("\t\t\t\t    \"regex\": false,\r\n");
      out.write("\t\t\t\t    // This is set to initial search automatic\r\n");
      out.write("\t\t\t\t   // \"search\": \"Fred\"\r\n");
      out.write("\t\t\t\t  },\r\n");
      out.write("\t\t\t  \"headerCallback\": function( thead, data, start, end, display ) {\r\n");
      out.write("\t\t\t\t    $(thead).find('th').eq(0).html( 'MongoID' );\r\n");
      out.write("\t\t\t\t    \r\n");
      out.write("\t\t\t\t  },  \r\n");
      out.write("\t  \t  \t\t\"columnDefs\": [\r\n");
      out.write("\t  \t  \t    \t\t\t\t{\r\n");
      out.write("\t  \t  \t        \t\t\t \t\"title\" : \"MongoID\",  \r\n");
      out.write("\t  \t  \t        \t\t\t    \"targets\": 0,\r\n");
      out.write("\t  \t  \t        \t\t\t\t\"orderable\" : true,\r\n");
      out.write("\t  \t  \t        \t\t\t\t\"searchable\": true,\r\n");
      out.write("\t\t  \t  \t        \t\t\t\"mData\" : null,\r\n");
      out.write("\t\t\t  \t  \t        \t\t\"mRender\" : function (data, type, row) {\r\n");
      out.write("\t\t\t\t  \t  \t        \t\tif (true) {\r\n");
      out.write("\t\t\t\t  \t  \t        \t\t\r\n");
      out.write("\t\t\t\t  \t  \t        \t\t\treturn '<a style=\"color:blue;\" href=\"projectInfo?projectId='+data[0]+'\"><span >'+data[0]+'</span></a>';\r\n");
      out.write("\t\t\t\t  \t  \t        \t\t}\r\n");
      out.write("\t\t\t  \t  \t        \t\t}\r\n");
      out.write("\t  \t  \t        \t\t\t },\r\n");
      out.write("\t  \t  \t        \t\t\t{\r\n");
      out.write("\t  \t  \t        \t\t\t\t\"title\" : \"College Name\",\r\n");
      out.write("\t   \t  \t\t       \t        \t\"targets\": 1,\r\n");
      out.write("\t   \t  \t\t       \t        \t\"searchable\": true,\r\n");
      out.write("\t  \t  \t        \t\t\t },\r\n");
      out.write("\t  \t  \t        \t\t\t {\r\n");
      out.write("\t  \t  \t        \t\t\t \t\"title\" : \"Approve To\",\r\n");
      out.write("\t   \t  \t\t       \t         \t\"targets\": 2,\r\n");
      out.write("\t   \t  \t\t       \t         \t\"searchable\": true\r\n");
      out.write("\t  \t  \t        \t\t\t },\r\n");
      out.write("\t  \t  \t        \t\t\t {\r\n");
      out.write("\t  \t  \t        \t\t\t \t\"title\" : \"Founder Name\",  \r\n");
      out.write("\t  \t  \t        \t\t\t    \"targets\": 3,\r\n");
      out.write("\t  \t  \t        \t\t\t\t\"orderable\" : true,\r\n");
      out.write("\t  \t  \t        \t\t\t\t\"searchable\": true,\r\n");
      out.write("\t\t  \t  \t        \t\t\t\"mData\" : null,\r\n");
      out.write("\t\t\t  \t  \t        \t\t\"mRender\" : function (data, type, row) {\r\n");
      out.write("\t\t\t  \t  \t        \t\t\t\r\n");
      out.write("\t\t\t  \t  \t        \t\tif (true) {\r\n");
      out.write("\t\t\t  \t  \t        \t\t\r\n");
      out.write("\t\t\t  \t  \t        \t\treturn '<span>'+data[3]+'</span>';\r\n");
      out.write("\t\t\t  \t  \t        \t\t/* return '<span>'+data[3]+'</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href=\"myBag_form?manifestNo='+data[0]+'\"><span class=\"glyphicon glyphicon-plus\"></span></a>'; */\r\n");
      out.write("\t\t\t  \t  \t        \t\t}\r\n");
      out.write("\t\t\t\t\t  \t  \t            else {\r\n");
      out.write("\t\t\t\t\t  \t  \t                \r\n");
      out.write("\t\t\t\t\t  \t  \t                return '<a href=\"manifestBag_list?manifestNo='+data[0]+'\"><span>'+data[3]+'</span></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class=\"glyphicon glyphicon-ban-circle\"></span>';\r\n");
      out.write("\t\t\t\t\t  \t  \t            }\r\n");
      out.write("\t\t\t  \t  \t        \t\t}\r\n");
      out.write("\t  \t  \t        \t\t\t },\r\n");
      out.write("\t  \t  \t        \t\t\t{\r\n");
      out.write("\t\t  \t  \t        \t\t\t \t\"title\" : \"Created At\",\r\n");
      out.write("\t\t   \t  \t\t       \t         \t\"targets\": 4,\r\n");
      out.write("\t\t   \t  \t\t       \t    \t\t\"visible\": true,\r\n");
      out.write("\t\t   \t  \t\t       \t         \t\"searchable\": true\r\n");
      out.write("\t\t  \t  \t        \t\t},\r\n");
      out.write("\t\t  \t  \t        \t    {\r\n");
      out.write("\t  \t  \t        \t\t\t \t\"title\" : \"Created By\",  \r\n");
      out.write("\t  \t  \t        \t\t\t    \"targets\": 5,\r\n");
      out.write("\t  \t  \t        \t\t\t\t\"orderable\" : true,\r\n");
      out.write("\t  \t  \t        \t\t\t\t\"visible\" : true\r\n");
      out.write("\t  \t  \t        \t\t\t },\r\n");
      out.write("\t  \t  \t        \t\t\t {\r\n");
      out.write("\t  \t  \t        \t\t\t \t\"title\" : \"Action\",  \r\n");
      out.write("\t  \t  \t        \t\t\t    \"targets\": 6,\r\n");
      out.write("\t  \t  \t        \t\t\t\t\"orderable\" : false,\r\n");
      out.write("\t  \t  \t        \t\t\t    \"data\": 0,\r\n");
      out.write("\t  \t  \t        \t\t\t    \"render\": function ( data, type, full, meta ) {\r\n");
      out.write("\t  \t  \t        \t\t\t      \t\t\t\treturn '<a style=\"color:blue;\" href=\"projectView?projectId='+data+'\"><span class=\"glyphicon glyphicon-eye-open\"></span></a>';\r\n");
      out.write("\t  \t  \t        \t\t\t      \t\t\t\t/*\r\n");
      out.write("\t  \t  \t        \t\t\t      \t\t\t\t&nbsp;&nbsp;<a href=\"manifest_edit?key='+data+'\"><span class=\"glyphicon glyphicon-pencil\"></span></a>&nbsp;&nbsp;\r\n");
      out.write("\t  \t  \t        \t\t\t      \t\t\t\t<a href=\"#\" id='+data+' onclick=\"getData(this.id);\"><span class=\"glyphicon glyphicon-trash\"></span></a>\r\n");
      out.write("\t  \t  \t        \t\t\t      \t\t\t\t*/\r\n");
      out.write("\t  \t  \t        \t\t\t    \t\t\t}\r\n");
      out.write("\t  \t  \t        \t\t\t  }\r\n");
      out.write("\t  \t  \t      \t\t\t\t],\t      \r\n");
      out.write("\t  \t      \t \"paging\": true,\r\n");
      out.write("\t  \t      \t \"responsive\": true,\r\n");
      out.write("\t  \t      \t // processing view for large amount of data durring sorting the inserted data\r\n");
      out.write("\t  \t      \t \"processing\": true\r\n");
      out.write("\t  \t      } );\r\n");
      out.write("\t\t\r\n");
      out.write("\t        } );\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
